/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vfqjobdslrlljxsclcrd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmcWpvYmRzbHJsbGp4c2NsY3JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk5OTc0OTAsImV4cCI6MjEwNTU3MzQ5MH0.it7JV-yLXOkmyT7Yoa_b0KHNcg6dPN2rPHCNUQB3W6s"
